<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. If you need some defines added, please contact */
/* Flywheel support at help@getflywheel.com.                                       */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'WAR');
define('DB_USER', 'root');
define('DB_PASSWORD', '');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix  = 'wp_';






/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          '^o4Y=Ly008v(k#%L,GP5[4g?]nI*0,HZ<_Z`jbOGi//^pwDbOiE/Q^&_SiJ|p:_Z');
define('SECURE_AUTH_KEY',   'pqJ@^}TRjD/zusZ0GCm;WFx#c|@K$-z(#7c?s~txoXtCB;1`OzsI*)4,q)K?s;[K');
define('LOGGED_IN_KEY',     '&AKQp(`qLm%sc$n/UHUy:68}jZB=>C!oC|!m<]-ue@+B9S3J:M61hPYPnpk^H2;(');
define('NONCE_KEY',         'i>%=}x.Tyce:*K6>`SKU`GL`2tXyn27tUwVCq,qU}j2f4(RNqRcClIE`,(Z()vR1');
define('AUTH_SALT',         '{X[]}jFp+=aCr_XKgfD=;zG![vb$TdOw%Q|<p@RdS[<N#m~@F/d,-<GAE{m;IK8T');
define('SECURE_AUTH_SALT',  'I2<qFZn.SF<LhnLs^ky1O|*pU7bFn05LEy#Za!hSHDK%&^LO;Pi>ijB2XK9n[+X2');
define('LOGGED_IN_SALT',    'g_?ss~lUuvvs>,xmlm+wAHzmy%->u`H5}X!6.}n:qzwuk0Uc;t&tEX2#Y-Q!)YLj');
define('NONCE_SALT',        '1f__V}1Bv0AoE|P5Q|zP_+zka^dR6hZyV&})GEPZs`U65wEWeni*:$yTqq;Mm-oJ');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);


/****************************************************************************/
/*                              Custom Content                              */
/****************************************************************************/
define('FORCE_SSL_ADMIN', false);


/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
